connector.name=clickhouse
connection-url=jdbc:ch://${ENV:CLICKHOUSE_HOST}:${ENV:CLICKHOUSE_PORT}/?ssl=true&sslmode=NONE&compress=false
connection-user=${ENV:CLICKHOUSE_USER}
connection-password=${ENV:CLICKHOUSE_PASSWORD}
