spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.type=rest
spark.sql.catalog.iceberg.uri=${ICEBERG_CATALOG_URI}
spark.sql.catalog.iceberg.warehouse=s3://${CATALOG_WAREHOUSE}
spark.sql.catalog.iceberg.io-impl=org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.iceberg.s3.path-style-access=true
spark.sql.defaultCatalog=iceberg
spark.eventLog.enabled=false
spark.sql.session.timeZone=UTC
